[package]
name = "cygrind-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-safe = { version = "0.47.0", features = ["gl"] }
logos = "0.12.0"
flo_curves = "0.6.0"